Fix Issue#13 +event update and list will hang
pyrox18/schedulerbot pull request #17
Opened 2018-10-16 00:32 UTC by jespirit

Fixes https://github.com/pyrox18/SchedulerBot/issues/13 by checking if the event name is empty or null and displaying "N/A" as a replacement for embed information.

2018-10-25 15:15 UTC, pyrox18 commented
See #13 for updates.

2018-10-27 02:28 UTC, pyrox18 requested changes

2018-10-27 02:28 UTC, pyrox18 commented on SchedulerBot.Client/Parsers/EventParser.cs
> +        private static void ParseEventTimestamps(string bodyString, string timezone, ref Event evt, bool update = false)
Can you change `update` to `isUpdate`? That makes it more obvious that it's a boolean.

2018-10-27 02:28 UTC, pyrox18 commented on SchedulerBot.Client/Parsers/EventParser.cs
> +                    }
Change this to the other form that you mentioned in the PR.

2018-10-27 05:18 UTC, jespirit commented
Ok, I made the changes.

One thing that strikes me as odd is that I _may_ have messed up a rebase because I don't understand why your previous commits are being included in this pull request.

2018-10-29 09:09 UTC, pyrox18 commented
Might be because you targeted the master branch instead of the dev branch.

2018-10-29 13:38 UTC, jespirit commented
Ahh, you're right. I noticed you changed it from Github. I didn't know you can do that.

2018-11-01 09:20 UTC, pyrox18 approved these changes

2018-11-01 09:27 UTC, merged